[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pranera_planning"
authors = [{ name = "Pranera Services & Solutions", email = "admin@pranera.in" }]
description = "Planning module for Pranera ERP"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []
